"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob
try:
    from distutils.core import setup
    import py2app, pygame
    from modulefinder import Module
    import glob, fnmatch
    import sys, os, shutil
except ImportError, message:
    raise SystemExit,  "Sorry, you must install py2app, pygame. %s" % message
APP = ['main.py']
DATA_FILES = []
fold = glob.glob('resources/font/')
fold2 = glob.glob('resources/image/')
fold3 = glob.glob('resources/sound/')
for i in fold:
    files = glob.glob(i + '*')
    DATA_FILES.append((i, files))
for i in fold2:
    files = glob.glob(i + '*')
    DATA_FILES.append((i, files))
for i in fold3:
    files = glob.glob(i + '*')
    DATA_FILES.append((i, files))
OPTIONS = {'argv_emulation': True, 'iconfile': 'resources/image/hero1.icns'}

setup(
    app = APP,
    name = "PlanHunter",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
